services:
  postgres:
    image: postgres:15
    container_name: trainer-postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mytrainer

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mytrainer

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mytrainer-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mytrainer

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mytrainer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mytrainer

volumes:
  pgdata:

networks:
  mytrainer:
    driver: bridge
